In [1]:

# coding: utf-8

# <img src='tensor.png'>

# <img src='parcs.png'>

import tensorflow as tf
from tensorflow import keras
import numpy as np

In [2]:
fashion_mnist = keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 2s 0us/step


In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
len(train_labels)

60000

In [5]:
np.unique(train_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [6]:
test_images.shape

(10000, 28, 28)

In [7]:
len(test_labels)

10000

In [8]:
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [9]:
train_images = train_images / 255.0

test_images = test_images / 255.0

In [10]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.summary()

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [12]:
model.fit(train_images, train_labels, epochs=5)

Epoch 1/5
60000/60000 [==============================] - 9s 157us/sample - loss: 0.4989 - acc: 0.8237
Epoch 2/5
60000/60000 [==============================] - 10s 163us/sample - loss: 0.3744 - acc: 0.8651
Epoch 3/5
60000/60000 [==============================] - 10s 159us/sample - loss: 0.3366 - acc: 0.8753
Epoch 4/5
60000/60000 [==============================] - 11s 177us/sample - loss: 0.3129 - acc: 0.8847
Epoch 5/5
60000/60000 [==============================] - 9s 157us/sample - loss: 0.2951 - acc: 0.8909


In [13]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

print('Test accuracy:', test_acc)

10000/10000 [==============================] - 1s 77us/sample - loss: 0.3414 - acc: 0.8753
Test accuracy: 0.8753


In [14]:
predictions = model.predict(test_images)

In [15]:
predictions[0]

array([4.8776288e-05, 2.3555097e-08, 1.1299878e-04, 5.4262950e-06,
       4.1167244e-05, 2.4334757e-02, 1.4450710e-04, 5.5091802e-02,
       2.3004576e-04, 9.1999054e-01], dtype=float32)

In [16]:
np.argmax(predictions[0])

9

In [17]:
test_labels[0]

9

In [18]:
img = test_images[0]

print(img.shape)

(28, 28)


In [19]:
img = (np.expand_dims(img,0))

print(img.shape)

(1, 28, 28)


In [20]:
predictions_single = model.predict(img)

print(predictions_single)

[[4.8776288e-05 2.3555097e-08 1.1299878e-04 5.4262950e-06 4.1167244e-05
  2.4334757e-02 1.4450710e-04 5.5091776e-02 2.3004555e-04 9.1999054e-01]]


In [21]:
np.argmax(predictions_single[0])

9