<img src='tensor.png'>

<img src='parcs.png'>

In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [26]:
mnist = keras.datasets.mnist #alterado de fashion_mnist para mnist de acordo com o exercicio

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [27]:
train_images.shape

(60000, 28, 28)

In [28]:
len(train_labels)

60000

In [29]:
np.unique(train_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [30]:
test_images.shape

(10000, 28, 28)

In [31]:
len(test_labels)

10000

In [32]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [33]:
train_images = train_images / 255.0

test_images = test_images / 255.0

In [34]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(50, activation=tf.nn.relu), #alterado de 128 para 50 neuronios na camada 1 de acordo com exercicio
    keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 50)                39250     
_________________________________________________________________
dense_3 (Dense)              (None, 10)                510       
Total params: 39,760
Trainable params: 39,760
Non-trainable params: 0
_________________________________________________________________


In [35]:
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [36]:
model.fit(train_images, train_labels, epochs=5)

Epoch 1/5
60000/60000 [==============================] - 8s 136us/sample - loss: 0.3216 - acc: 0.9095
Epoch 2/5
60000/60000 [==============================] - 9s 143us/sample - loss: 0.1571 - acc: 0.9533
Epoch 3/5
60000/60000 [==============================] - 8s 130us/sample - loss: 0.1177 - acc: 0.9652
Epoch 4/5
60000/60000 [==============================] - 8s 135us/sample - loss: 0.0949 - acc: 0.9722
Epoch 5/5
60000/60000 [==============================] - 8s 134us/sample - loss: 0.0787 - acc: 0.9765


In [37]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

print('Test accuracy:', test_acc)

10000/10000 [==============================] - 1s 74us/sample - loss: 0.0991 - acc: 0.9700
Test accuracy: 0.97


In [38]:
predictions = model.predict(test_images)

In [39]:
predictions[0]

array([1.2084483e-07, 2.8242887e-06, 2.4254226e-05, 9.7315980e-04,
       5.7394387e-09, 9.1614529e-06, 1.2084736e-07, 9.9897063e-01,
       8.3774339e-06, 1.1422421e-05], dtype=float32)

In [40]:
np.argmax(predictions[0])

7

In [41]:
test_labels[0]

7

In [42]:
img = test_images[0]

print(img.shape)

(28, 28)


In [43]:
img = (np.expand_dims(img,0))

print(img.shape)

(1, 28, 28)


In [44]:
predictions_single = model.predict(img)

print(predictions_single)

[[1.2084516e-07 2.8242914e-06 2.4254248e-05 9.7316073e-04 5.7394609e-09
  9.1614620e-06 1.2084770e-07 9.9897063e-01 8.3774412e-06 1.1422433e-05]]


In [45]:
np.argmax(predictions_single[0])

7